-- MySQL Script generated by MySQL Workbench
-- Tue Jan 28 20:18:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ece1779_a1` DEFAULT CHARACTER SET utf8 ;
USE `ece1779_a1` ;

DROP TABLE IF EXISTS Image;
DROP TABLE IF EXISTS User;

-- -----------------------------------------------------
-- Table `ece1779_a1`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ece1779_a1`.`User` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ece1779_a1`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ece1779_a1`.`Image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(200) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `currenttime` VARCHAR(45) NOT NULL,
  `pictype` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `username_idx` (`username` ASC),
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `ece1779_a1`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
